=== egekorkan/plugins/plugin.schema.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "type": "object",
  "properties": {
    "uid": { "type": "string", "pattern": "^(ti-|tm-|wi-).*" },
    "type": {
      "type": "string",
      "enum": ["thing-importer", "thing-model", "widget"]
    },
    "version": { "type": "string", "pattern": "(0-9)*.(0-9)*.(0-9)*." },
    "status": { "type": "string", "enum": ["stable", "beta", "requested"] },
    "category": { "type": "string", "enum": ["official", "community"] },
    "name": { "type": "string" },
    "title": { "type": "string" },
    "description": { "type": "string" },
    "description": { "type": "string", "maxLength": 250 },
    "keywords": {
      "type": "array",
      "items": [{ "type": "string" }]
    },
    "main": { "type": "string", "pattern": "uri" },
    "display": {
      "type": "object",
      "properties": {
        "imageUrl": { "type": "string", "format": "uri" },
        "color": { "type": "string", "format": "hexcolor" },
        "screenshots": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "label": { "type": "string" },
              "src": {
                "type": "string",
                "contentMediaType": "image/png"
              }
            },
            "required": ["src"]
          }
        }
      },
      "required": ["imageUrl"]
    },
    "links": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "rel": { "type": "string" },
            "href": { "type": "string", "format": "uri" },
            "title": { "type": "string" },
            "type": { "type": "string" }
          },
          "required": ["rel", "href"]
        }
      ]
    }
  }
}

=== egekorkan/plugins/packages/web-components/eventlog/plugin.json
{
  "uid": "eventlog-widget",
  "version": "1.0.0",
  "status": "beta",
  "type": "widget",
  "name": "Alert table",
  "description": "Alert table widget for Asterisc",
  "keywords": ["asterisc", "plugin", "widget", "eventlog"],
  "main": "https://raw.githubusercontent.com/asteriscio/plugins/main/packages/web-components/eventlog/src/index.js",
  "links": [
    {
      "rel": "icon",
      "href": "https://raw.githubusercontent.com/asteriscio/plugins/main/packages/web-components/eventlog/src/assets/icon.svg"
    },
    {
      "rel": "screenshot",
      "src": "https://raw.githubusercontent.com/asteriscio/plugins/main/packages/web-components/eventlog/src/assets/images/screenshot.png"
    },
    {
      "rel": "author",
      "href": "https://asterisc.io",
      "title": "Asterisc GmbH"
    },
    {
      "rel": "homepage",
      "href": "https://github.com/asteriscio/plugins/tree/main/packages/web-components/eventlog"
    },
    {
      "rel": "repository",
      "href": "https://github.com/asteriscio/plugins"
    },
    {
      "rel": "license",
      "href": "https://raw.githubusercontent.com/asteriscio/plugins/main/packages/web-components/eventlog/LICENSE"
    }
  ]
}

=== egekorkan/plugins/packages/web-components/switch/plugin.json
{
  "uid": "switch-widget",
  "version": "1.0.0",
  "status": "beta",
  "type": "widget",
  "name": "Switch",
  "description": "Switch widget for Asterisc",
  "keywords": ["asterisc", "plugin", "widget", "switch"],
  "main": "https://raw.githubusercontent.com/asteriscio/plugins/main/packages/web-components/switch/src/index.js",
  "links": [
    {
      "rel": "icon",
      "href": "https://raw.githubusercontent.com/asteriscio/plugins/main/packages/web-components/switch/src/assets/icon.svg"
    },
    {
      "rel": "screenshot",
      "src": "https://raw.githubusercontent.com/asteriscio/plugins/main/packages/web-components/eventlog/src/assets/images/screenshot.png"
    },
    {
      "rel": "author",
      "href": "https://asterisc.io",
      "title": "Asterisc GmbH"
    },
    {
      "rel": "homepage",
      "href": "https://github.com/asteriscio/plugins/tree/main/packages/web-components/switch"
    },
    {
      "rel": "repository",
      "href": "https://github.com/asteriscio/plugins"
    },
    {
      "rel": "license",
      "href": "https://raw.githubusercontent.com/asteriscio/plugins/main/packages/web-components/switch/LICENSE"
    }
  ]
}

=== egekorkan/plugins/packages/web-components/table/plugin.json
{
  "uid": "table-widget",
  "version": "1.0.0",
  "status": "beta",
  "type": "widget",
  "name": "Table",
  "description": "Table widget for Asterisc",
  "keywords": ["asterisc", "plugin", "widget", "table"],
  "main": "https://raw.githubusercontent.com/asteriscio/plugins/main/packages/web-components/table/src/index.js",
  "links": [
    {
      "rel": "icon",
      "href": "https://raw.githubusercontent.com/asteriscio/plugins/main/packages/web-components/table/src/assets/icon.svg"
    },
    {
      "rel": "screenshot",
      "src": "https://raw.githubusercontent.com/asteriscio/plugins/main/packages/web-components/eventlog/src/assets/images/screenshot.png"
    },
    {
      "rel": "author",
      "href": "https://asterisc.io",
      "title": "Asterisc GmbH"
    },
    {
      "rel": "homepage",
      "href": "https://github.com/asteriscio/plugins/tree/main/packages/web-components/table"
    },
    {
      "rel": "repository",
      "href": "https://github.com/asteriscio/plugins"
    },
    {
      "rel": "license",
      "href": "https://raw.githubusercontent.com/asteriscio/plugins/main/packages/web-components/table/LICENSE"
    }
  ]
}

=== egekorkan/plugins/packages/web-components/slider/plugin.json
{
  "uid": "slider-widget",
  "version": "1.0.0",
  "status": "beta",
  "type": "widget",
  "name": "Slider",
  "description": "Slider widget for Asterisc",
  "keywords": ["asterisc", "plugin", "widget", "slider"],
  "main": "https://raw.githubusercontent.com/asteriscio/plugins/main/packages/web-components/slider/src/index.js",
  "links": [
    {
      "rel": "icon",
      "href": "https://raw.githubusercontent.com/asteriscio/plugins/main/packages/web-components/slider/src/assets/icon.svg"
    },
    {
      "rel": "screenshot",
      "src": "https://raw.githubusercontent.com/asteriscio/plugins/main/packages/web-components/eventlog/src/assets/images/screenshot.png"
    },
    {
      "rel": "author",
      "href": "https://asterisc.io",
      "title": "Asterisc GmbH"
    },
    {
      "rel": "homepage",
      "href": "https://github.com/asteriscio/plugins/tree/main/packages/web-components/slider"
    },
    {
      "rel": "repository",
      "href": "https://github.com/asteriscio/plugins"
    },
    {
      "rel": "license",
      "href": "https://raw.githubusercontent.com/asteriscio/plugins/main/packages/web-components/slider/LICENSE"
    }
  ]
}

=== egekorkan/plugins/packages/web-components/stepper/plugin.json
{
  "uid": "stepper-widget",
  "version": "1.0.0",
  "type": "widget",
  "name": "Stepper",
  "description": "Stepper widget for Asterisc",
  "keywords": ["asterisc", "plugin", "widget", "stepper"],
  "main": "https://raw.githubusercontent.com/asteriscio/plugins/main/packages/web-components/stepper/src/index.js",
  "links": [
    {
      "rel": "icon",
      "href": "https://raw.githubusercontent.com/asteriscio/plugins/main/packages/web-components/stepper/src/assets/icon.svg",
      "type": "image/svg"
    },
    {
      "rel": "screenshot",
      "src": "https://raw.githubusercontent.com/asteriscio/plugins/main/packages/web-components/eventlog/src/assets/images/screenshot.png",
      "type": "image/png"
    },
    {
      "rel": "author",
      "href": "https://asterisc.io",
      "type": "text/html"
    },
    {
      "rel": "homepage",
      "href": "https://github.com/asteriscio/plugins/tree/main/packages/web-components/stepper",
      "type": "text/html"
    },
    {
      "rel": "repository",
      "href": "https://github.com/asteriscio/plugins",
      "type": "text/html"
    },
    {
      "rel": "license",
      "href": "https://raw.githubusercontent.com/asteriscio/plugins/main/packages/web-components/stepper/LICENSE",
      "type": "text/html"
    }
  ]
}

=== egekorkan/plugins/packages/web-components/chart/plugin.json
{
  "uid": "chart-widget",
  "version": "1.0.0",
  "type": "widget",
  "name": "Chart",
  "description": "Chart widget for Asterisc",
  "keywords": ["asterisc", "plugin", "widget", "chart"],
  "main": "https://raw.githubusercontent.com/asteriscio/plugins/main/packages/web-components/chart/src/index.js",
  "links": [
    {
      "rel": "icon",
      "href": "https://raw.githubusercontent.com/asteriscio/plugins/main/packages/web-components/chart/src/assets/icon.svg",
      "type": "image/svg"
    },
    {
      "rel": "author",
      "href": "https://asterisc.io",
      "type": "text/html"
    },
    {
      "rel": "homepage",
      "href": "https://github.com/asteriscio/plugins/tree/main/packages/web-components/chart",
      "type": "text/html"
    },
    {
      "rel": "repository",
      "href": "https://github.com/asteriscio/plugins",
      "type": "text/html"
    },
    {
      "rel": "license",
      "href": "https://raw.githubusercontent.com/asteriscio/plugins/main/packages/web-components/chart/LICENSE",
      "type": "text/html"
    }
  ]
}

=== egekorkan/plugins/packages/web-components/map/plugin.json
{
  "uid": "map-widget",
  "version": "1.0.0",
  "type": "widget",
  "name": "Map",
  "description": "Map widget for Asterisc",
  "keywords": ["asterisc", "plugin", "widget", "map"],
  "main": "https://raw.githubusercontent.com/asteriscio/plugins/main/packages/web-components/map/src/index.js",
  "links": [
    {
      "rel": "icon",
      "href": "https://raw.githubusercontent.com/asteriscio/plugins/main/packages/web-components/map/src/assets/icon.svg",
      "type": "image/svg"
    },
    {
      "rel": "screenshot",
      "src": "https://raw.githubusercontent.com/asteriscio/plugins/main/packages/web-components/eventlog/src/assets/images/screenshot.png",
      "type": "image/png"
    },
    {
      "rel": "author",
      "href": "https://asterisc.io",
      "type": "text/html"
    },
    {
      "rel": "homepage",
      "href": "https://github.com/asteriscio/plugins/tree/main/packages/web-components/map",
      "type": "text/html"
    },
    {
      "rel": "repository",
      "href": "https://github.com/asteriscio/plugins",
      "type": "text/html"
    },
    {
      "rel": "license",
      "href": "https://raw.githubusercontent.com/asteriscio/plugins/main/packages/web-components/map/LICENSE",
      "type": "text/html"
    }
  ]
}

=== egekorkan/plugins/packages/web-components/text/plugin.json
{
  "uid": "text-widget",
  "version": "1.0.0",
  "status": "beta",
  "type": "widget",
  "name": "Text",
  "description": "Text widget for Asterisc",
  "keywords": ["asterisc", "plugin", "widget", "text"],
  "main": "https://raw.githubusercontent.com/asteriscio/plugins/main/packages/web-components/text/src/index.js",
  "links": [
    {
      "rel": "icon",
      "href": "https://raw.githubusercontent.com/asteriscio/plugins/main/packages/web-components/text/src/assets/icon.svg"
    },
    {
      "rel": "screenshot",
      "src": "https://raw.githubusercontent.com/asteriscio/plugins/main/packages/web-components/eventlog/src/assets/images/screenshot.png"
    },
    {
      "rel": "author",
      "href": "https://asterisc.io",
      "title": "Asterisc GmbH"
    },
    {
      "rel": "homepage",
      "href": "https://github.com/asteriscio/plugins/tree/main/packages/web-components/text"
    },
    {
      "rel": "repository",
      "href": "https://github.com/asteriscio/plugins"
    },
    {
      "rel": "license",
      "href": "https://raw.githubusercontent.com/asteriscio/plugins/main/packages/web-components/text/LICENSE"
    }
  ]
}
